# See:
#   https://docs.travis-ci.com/user/customizing-the-build/
#   https://docs.travis-ci.com/user/languages/python

language: python

python:
  - "pypy"
  - "pypy3"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

matrix:
  fast_finish: true
  allow_failures:
    - python: "pypy"
    - python: "pypy3"
    - python: "3.5-dev"
    - python: "nightly"

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run --source=botutil -m unittest discover -s tests

after_success:
  - pip install coveralls
  - coveralls

after_script:
  - coverage report
  - pip install pep8 #pyflakes
 #- pyflakes *.py | tee >(wc -l)
  - pep8 --statistics --count *.py
